"""empty message

Revision ID: 09bffe8084c5
Revises: 9aa1c78c5f35
Create Date: 2021-05-20 12:13:38.790801

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '09bffe8084c5'
down_revision = '9aa1c78c5f35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_password', sa.String(length=20), nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=80), nullable=True))
    op.drop_column('user', '_password')
    # ### end Alembic commands ###
